services:
  state_machine_service:
    build: ./src/state_machine/
    volumes:
      - ./deployment/config.json:/app/config.json
    restart: always
  
  valves_service:
    build: ./src/valves_node/
    privileged: true
    volumes:
      - ./deployment/config.json:/app/config.json
    restart: always

  # sensors_service:
  #   build: ./src/sensors_node/
  #   ipc: "host"
  #   volumes:
  #     - ./deployment/config.json:/app/config.json
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   restart: always
  
  
  # vfd_service:
  #   build: ./src/vfd_node/
  #   ipc: "host"
  #   volumes:
  #     - ./deployment/config.json:/app/config.json
  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   restart: always

  serial_service:
    build: ./src/serial_service/
    volumes:
      - ./deployment/config_modified.json:/app/config.json
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always