services:
  state_machine_service:
    build: ./src/state_machine/
    volumes:
      - ./deployment/config/config.json:/app/config.json
      - ./deployment/config/variables.json:/app/variables.json
      - ./deployment/logs/state_machine:/app/logs
    restart: always
  
  # valves_service:
  #   build: ./src/valves_node/
  #   privileged: true
  #   volumes:
  #     - ./deployment/config/config.json:/app/config.json
  #     - ./deployment/logs/valve_controller:/app/logs

  #   restart: always

  # serial_service:
  #   build: ./src/serial_service/
  #   volumes:
  #     - ./deployment/config/config.json:/app/config.json
  #     - ./deployment/logs/serial_com:/app/logs

  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   restart: always


  fake_serial_service:
    build: ./src/fake_serial_service/
    volumes:
      - ./deployment/config/config.json:/app/config.json
      - ./deployment/logs/serial_service:/app/logs

    restart: always

  fake_valves_service:
    build: ./src/fake_valves_node/
    volumes:
      - ./deployment/config/config.json:/app/config.json
      - ./deployment/logs/valve_controller:/app/logs
    restart: always


  # serial_service:
  #   build: ./src/serial_service/
  #   volumes:
  #     - ./deployment/config/config.json:/app/config.json
  #     - ./deployment/logs/serial_com:/app/logs

  #   devices:
  #     - /dev/ttyACM0:/dev/ttyACM0
  #   restart: always

  # fake_serial_service:
  #   build: ./src/fake_serial_service/
  #   volumes:
  #     - ./deployment/config/config.json:/app/config.json
  #   restart: always




